[package]
name = "atlas-storyboard"
version = "0.1.0"
description = "Интерактивная карта историй и мест"
authors = ["you"]
edition = "2021"

[lib]
name = "atlas_storyboard_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde_json = "1"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-log = "2"
log = "0.4"
